### ISSUE TITLE
Filter filtert auch Objekte die keine Content-Element sind

### ISSUE THREAD

**Issue by LinkingYou** [terminal42/contao-ce-access#13]
Hi,

wir nutzen Contao 4.4.5 mit folgenden Erweiterungen: Ce-Access (2.0.4), RocksolidSlider.

Wenn ein normaler User (nicht Admin) einen Slide editieren möchte, dann läuft das auch durch die Funktion "filterContentElements". Hier wird dann die ID des Slides genommen und in der tl_content nachgesehen, welches Element das betrifft. Hier kommt dann ein "zufälliges" Element zurück und reagiert mit "Attempt to access restricted content element".

Ich weiß nicht, ob es zu einfach ist. Evtl. könnte man in die Funktion am Anfang nach dem "isAdmin"-Check folgende Zeilen einbauen:

```
        // Filter only elements in tl_content
        if ($dc->ptable != 'tl_content') {
            return;
        }
```

Im Test hat das jedenfalls gut funktioniert.

Gruß
Franky

**Comment by ausi** [comment]
Ich konnten den Fehler nicht reproduzieren.

Ich verstehe auch nicht warum `$dc->ptable` den Wert `'tl_content'` haben sollte, die parent table ist ja eher `tl_article`, `tl_news` oder eben im falle des Sliders `tl_rocksolid_slide`.

Wie genau sieht die URL in deinem Test aus?  
Korrekt wäre `/contao?do=rocksolid_slider&table=tl_content&id=[SLIDE-ID]&rt=...&ref=...`

**Comment by LinkingYou** [comment]
Der Link in diesem Fall sieht so aus:
`http://127.0.0.1:8000/contao?do=rocksolid_slider&table=tl_content&id=5&rt=N8KQU0URhPJFD8rY1mwm2oZpLkBmNwMyEjVPjrwVulI&ref=O5L2qLFj
`

Beim Aufruf wird auf /app.php?act=error weitergeleitet.

Alle anderen Slides kann dieser User normal bearbeiten. Ein Admin kann auch diesen Slide bearbeiten.

**Comment by aschempp** [comment]
Ich denke das Problem wurde in der 2.0.5 behoben.
