### ISSUE TITLE
Sperrung ganzer Artikel für Editoren

### ISSUE THREAD

**Issue by HumanDigital** [terminal42/contao-ce-access#14]
Die Funktion  "CeAccess::filterContentElements($dc)" erzeugt fälschlicherweise eine Fehlermeldung beim Öffnen eines Artikels, wenn dieser Artikel zufällig die gleiche ID hat, wie ein Inhaltselement, das der betroffene Benutzer nicht verwenden darf.

Hendrik hatte mir die Info gegeben, dass  act auf null zu prüfen ist. Nach einem Update von ce-access taucht das Problem nun wieder auf, darum gebe ich es hier nochmal als Issue ein. 

Bugfix:
CeAccess.php Zeile 85

bisher:
             if (!in_array(\Input::get('act'), array('show', 'create', 'select', 'editAll'), true)
                	&& !(\Input::get('act') === 'paste' && \Input::get('mode') === 'create')
             ) {
 
Bugfix von Hendrik

		if (\Input::get('act') != null
                && !in_array(\Input::get('act'), array('show', 'create', 'select', 'editAll'), true)
                && !(\Input::get('act') === 'paste' && \Input::get('mode') === 'create')
            ) {

**Comment by aschempp** [comment]
Verwendest du die neuste Version? Denn die Zeile 85 wird bei leerem `act` gar nicht erreicht (siehe https://github.com/terminal42/contao-ce-access/blob/master/CeAccess.php#L52) ?

**Comment by HumanDigital** [comment]
Danke für den Hinweis.
Es scheint wohl nicht die allerneuste Version gewesen zu sein, die den Fehler wieder aufgeworfen hat. Habe erst nachher auf die neuste Version aktualisiert und dann nicht nochmal ohne Bugfix geprüft.

Habe nun die aktuellste Version von ce-access in der Erweiterungsverwaltung nochmals repariert und nun kommt der Fehler ohne Bugfix nicht mehr. Vielen Dank !
