### ISSUE TITLE
Do not use getContentElements() in migration

### ISSUE THREAD

**Issue by m-vo** [terminal42/contao-ce-access#15]
Just a short memo for the develop branch I noticed when implementing https://github.com/contao/installation-bundle/pull/94:

Changing `getContentElements()` from https://github.com/terminal42/contao-ce-access/blob/5028efff9aa989aaa1910161301eabe427d5c4ad/CeAccess.php#L176-L193 to  https://github.com/terminal42/contao-ce-access/blob/dd35f7d67bfa72266ae024a4f28fff235809b547/CeAccess.php#L187-L220 will break https://github.com/terminal42/contao-ce-access/blob/5028efff9aa989aaa1910161301eabe427d5c4ad/config/runonce.php#L44

**Comment by aschempp** [comment]
There will not be any new features to this extension, as it has been integrated into Contao 4.9
