### ISSUE TITLE
Limit access of content elements to specific user-groups

### ISSUE THREAD

**Issue by saress** [terminal42/contao-ce-access#16]
I have suggested this feature for the contao-node bundle, but it was not the right place, please see:

https://github.com/terminal42/contao-node/issues/7#issue-464594496 and
https://github.com/terminal42/contao-node/issues/7#issuecomment-508761320

So hopefully this bundle fits better :-)

Kind regards,
Sares

**Comment by aschempp** [comment]
There will not be any new features to this extension, as it has been integrated into Contao 4.9
