### ISSUE TITLE
Support latest Contao 4.9 LTS

### ISSUE THREAD

**Issue by cgoIT** [terminal42/contao-ce-access#17]
Hi,

thanks for this great extension.

I'm using this extension in one of my sites. Are there any plans to support the latest LTS-Version of contao?

**Comment by richardhj** [comment]
ce_access is now part of Contao since version 4.9.0. You should be safe to remove this package from your composer.json.

**Comment by cgoIT** [comment]
Wow. This is something I would call a quick reply. ;)
Thanks for the information. I will have a look at it. Have a nice weekend.

**Comment by richardhj** [comment]
README updated in 565b933368eedf3637a5c6a5b6345d0b38fd991a :-)
