### ISSUE TITLE
Have choice between "Add" and "Modify" CE

### ISSUE THREAD

**Issue by JLBA** [terminal42/contao-ce-access#3]
Hello,
Thanks for this very useful extension but for the moment, checking some CE in group permissions let users add and modify CE. Is it possible to have choice between letting them add and/or modify CE ?

**Comment by aschempp** [comment]
you mean it should be possible to allow editing existing elements but not adding a new element of certain type?

**Comment by JLBA** [comment]
Hi Andreas,
That's it. For we can define more precisely which ce a user can add and/or modify and which he can not.
Thanks.

**Comment by aschempp** [comment]
There will not be any new features to this extension, as it has been integrated into Contao 4.9

**Comment by JLBA** [comment]
> There will not be any new features to this extension, as it has been integrated into Contao 4.9

Very good news ! i was waiting for this from a long time.
