### ISSUE TITLE
Inhaltselemente lassen sich nicht unsichtbar/sichtbar schalten mit dem Augensymbol

### ISSUE THREAD

**Issue by JensenR** [terminal42/contao-ce-access#5]
Hallo, leider haben die Augensymbole zum sichtbar / unsichtbar machen keine Funktion bei installiertem ce-access. Wie kann der Fehler gelöst werden?

**Comment by Toflar** [comment]
Wie lässt sich das reproduzieren?

**Comment by aschempp** [comment]
Sollte im Hotfix-Branch bereits behoben sein, kannst du den testen?

**Comment by dhe** [comment]
Hallo,
hatte dasselbe Problem, nach dem Einspielen des Hotfixes 2.0.4 bekomme ich folgende Fehlermeldung:

> Fatal error: Uncaught exception Error with message Using $this when not in object context thrown in system/modules/core/dca/tl_content.php on line 1601
#0 system/modules/ce-access/CeAccess.php(147): tl_content::deleteElement(Array, 'act=delete', 'Element l\xC3\xB6sche...', 'Inhaltselement ...', 'delete.gif', ' class="delete"...', 'tl_content', NULL, NULL, false, NULL, NULL, Object(Contao\DC_Table))
#1 system/modules/core/classes/DataContainer.php(683): CeAccess->deleteButton(Array, 'act=delete', 'Element l\xC3\xB6sche...', 'Inhaltselement ...', 'delete.gif', ' class="delete"...', 'tl_content', NULL, NULL, false, NULL, NULL, Object(Contao\DC_Table))
#2 system/modules/core/drivers/DC_Table.php(4241): Contao\DataContainer->generateButtons(Array, 'tl_content', NULL, false, NULL, NULL, NULL)
#3 system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->parentView()
#4 system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}

Hilft das beim Bugfxing weiter?

**Comment by HStrandel** [comment]
Ich habe Contao 3.5.27 installiert zusammen mit ce-access 2.0.2.
Wie mein Vorredner wird der Klick auf das "Augen"-Symbol nicht mehr registriert.
Nach der Installation des Hotfix 2.0.4 erhalte ich folgende Fehlermeldung:

**Fatal error:** Using $this when not in object context in /home/xyz/public_html/system/modules/core/dca/tl_content.php on line 1601

**Comment by aschempp** [comment]
Fixed in 8b340e0f899e6a58f578f5a94c9fa1a217e213e2 and released as 2.0.4
