### ISSUE TITLE
Issue with HTML content

### ISSUE THREAD

**Issue by WebNetCrea** [terminal42/contao-ce-access#7]
Hi,

I have HTML elements in articles, if I do not check enable HTML content the users have an error message, when i check enable HTML everything is ok

**Comment by jaynoe** [comment]
Ich habe dieses Problem auch. Aber nicht nur mit dem HTML Element sondern unteranderem auch bei "module", "headline" oder "form" Elemente. Passiert häufiger in der letzten Zeit in Contao Versionen 3.5.30 oder 3.5.31.

Die Fehlermeldung im System-Log sieht dann so aus: 
`Attempt to access restricted content element "module"` etc

**Comment by aschempp** [comment]
This should already be fixed in the latest version (2.0.5) ?

**Comment by jaynoe** [comment]
In den Installationen nutzen wir noch die alte Erweiterungsverwaltung. Und dort findet man die 2.0.5 Version nicht. Also müsste man für die 2.0.5 Version entweder das Composer Plugin installieren oder es manuell updaten?

**Comment by aschempp** [comment]
I just added 2.0.5 to the Extension Repository.

**Comment by epsreps** [comment]
i still have this issue in contao 4.8 in multiple edit mode.

**Comment by Toflar** [comment]
4.8 is not maintained anymore so there's no reason for us to look into that.

**Comment by epsreps** [comment]
i see. thanks toflar for your quick response. i will check this in 4.9
